version: '3.4'
services:
  metad:
    image: vesoft/nebula-metad:v2.5.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=metad
      - --ws_ip=metad
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559:9559
      - 19559:19559
      - 19560:19560
    volumes:
      - ./data/meta0:/data/meta
      - ./logs/meta0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  storaged:
    image: vesoft/nebula-storaged:v2.5.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
      - --ws_ip=storaged
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779:9779
      - 19779:19779
      - 19780:19780
    volumes:
      - ./data/storage0:/data/storage
      - ./logs/storage0:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  graphd:
    image: vesoft/nebula-graphd:v2.5.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=metad:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - storaged
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9669:9669"
      - 19669:19669
      - 19670:19670
    volumes:
      - ./logs/graph:/logs
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  nebula_http_gateway:
    image: vesoft/nebula-http-gateway:v2
    depends_on:
      - storaged
      - graphd
    ports:
      - "8080:8080"
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
# Handle the cross domain issue.
## Use localhost-ssl-proxy to handle cross domain issue.
  localhost-ssl-proxy:
    image: kineviz/localhost-ssl-proxy:latest
    depends_on:
      - nebula_http_gateway
      - graphd
    command: -h nebula_http_gateway -p 8080 -s false 
    ports:
      - 9080:9443
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

networks:
  nebula-net:
